apiVersion: v1
kind: Namespace
metadata:
  name: reports
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: steamreportsapi
  namespace: reports
spec:
  selector:
    matchLabels:
      app: steamreportsapi-pod
  template:
    metadata:
      labels:
        app: steamreportsapi-pod
    spec:
      containers:
        - name: steamreportsapi-container
          image: lgpinguim/steamreportsapi:latest
          resources:
            limits:
              memory: "1024Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          env:
            - name: REDIS_HOST
              value: redis-service.reports.svc.cluster.local
            - name: REDIS_PORT
              value: "6379"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: reports
spec:
  selector:
    matchLabels:
      app: redis-pod
  template:
    metadata:
      labels:
        app: redis-pod
    spec:
      containers:
        - name: redis-container
          image: redis
          resources:
            limits:
              memory: "1024Mi"
              cpu: "500m"
          ports:
            - containerPort: 6379