version: '3.4'

services:
  steamreportsapi:
    image: ${DOCKER_REGISTRY-}steamreportsapi
    build:
      context: .
      dockerfile: SteamReportsAPI/Dockerfile
    ports:
      - "8080:80"
    environment:
        - REDIS_HOST:"redis"
        - REDIS_PORT:6379   
    networks:
      - steamreportsnet       
    depends_on:
      - redis
    volumes: 
       - ./SteamReportsAPI/steam.db:/app/steam.db

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - steamreportsnet

networks:
  steamreportsnet:
    driver: bridge

