version: '3.4'

services:
  steamreportsapi:
    image: ${DOCKER_REGISTRY-}steamreportsapi
    build:
      context: .
      dockerfile: SteamReportsAPI/Dockerfile
    ports:
      - "8080:80"
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
        - REDIS_HOST:"redis"
        - REDIS_PORT:6379       
          
    depends_on:
      - redis

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

