apiVersion: v1
kind: Service
metadata:
  name: steamreportsapi-service
  namespace: reports
spec:
  selector:
    app: steamreportsapi-pod
  ports:
  - port: 80
    nodePort: 30002  
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: reports
spec:
  selector:
    app: redis-pod
  ports:
    - port: 6379
      targetPort: 6379
  type: ClusterIP
